module Responses
  SMUGMUG = {
    :albums => {
      :get_heavy => [{"id" => 24080102, "Key" => "Ka2Wx9", "Backprinting" => "", "BoutiquePackaging" => 2, "CanRank" => true, "Category" => {"id" => 0, "Name" => "Other"}, "Clean" => false, "ColorCorrection" => 2, "Comments" => true, "Description" => "This is a description, it's also new.", "EXIF" => true, "External" => false, "FamilyEdit" => false, "Filenames" => false, "FriendEdit" => false, "Geography" => true, "Header" => false, "HideOwner" => false, "ImageCount" => 2, "InterceptShipping" => 2, "Keywords" => "", "Larges" => true, "LastUpdated" => "2012-07-16 20:41:22", "NiceName" => "Test", "Originals" => false, "PackagingBranding" => true, "Password" => "foobar123123321", "PasswordHint" => "", "Passworded" => true, "Position" => 1, "Printable" => true, "ProofDays" => 0, "Protected" => true, "Public" => false, "Share" => true, "SmugSearchable" => false, "SortDirection" => false, "SortMethod" => "Position", "SquareThumbs" => true, "Template" => {"id" => 0}, "Theme" => {"id" => 1, "Name" => "default"}, "Title" => "Test", "URL" => "http://zapfolio.smugmug.com/Other/Test/24080102_Ka2Wx9", "UnsharpAmount" => 0.2, "UnsharpRadius" => 1, "UnsharpSigma" => 1, "UnsharpThreshold" => 0.05, "UploadKey" => "", "Watermark" => {"id" => 0, "Name" => "SmugMug"}, "Watermarking" => false, "WorldSearchable" => false, "X2Larges" => false, "X3Larges" => false, "XLarges" => false}, {"id" => 24080103, "Key" => "Ka2Wx4", "Backprinting" => "", "BoutiquePackaging" => 2, "CanRank" => true, "Category" => {"id" => 0, "Name" => "Other"}, "Clean" => false, "ColorCorrection" => 2, "Comments" => true, "Description" => "This is a description.", "EXIF" => true, "External" => false, "FamilyEdit" => false, "Filenames" => false, "FriendEdit" => false, "Geography" => true, "Header" => false, "HideOwner" => false, "ImageCount" => 1, "InterceptShipping" => 2, "Keywords" => "", "Larges" => false, "LastUpdated" => "2012-07-16 21:50:22", "NiceName" => "Test", "Originals" => false, "PackagingBranding" => true, "Password" => "", "PasswordHint" => "", "Passworded" => false, "Position" => 1, "Printable" => true, "ProofDays" => 0, "Protected" => true, "Public" => true, "Share" => true, "SmugSearchable" => false, "SortDirection" => false, "SortMethod" => "Position", "SquareThumbs" => true, "Template" => {"id" => 0}, "Theme" => {"id" => 1, "Name" => "default"}, "Title" => "Test 2", "URL" => "http://zapfolio.smugmug.com/Other/Test/24080103_Ka2Wx4", "UnsharpAmount" => 0.2, "UnsharpRadius" => 1, "UnsharpSigma" => 1, "UnsharpThreshold" => 0.05, "UploadKey" => "", "Watermark" => {"id" => 0, "Name" => "SmugMug"}, "Watermarking" => false, "WorldSearchable" => false, "X2Larges" => false, "X3Larges" => false, "XLarges" => false}]
    },

    :images => {
      :get_extras_1 => {"id" => 24080102, "Key" => "Ka2Wx9", "ImageCount" => 2, "Images" => [{"id" => 1955880317, "Key" => "HskGh8W", "Caption" => "", "Date" => "2012-07-09 19:50:06", "Format" => "JPG", "Height" => 1025, "Hidden" => false, "LastUpdated" => "2012-07-09 19:50:20", "Width" => 768}, {"id" => 1955880811, "Key" => "K6X9hwr", "Caption" => "Another test caption", "Date" => "2012-07-09 18:50:07", "Format" => "PNG", "Height" => 800, "Hidden" => true, "LastUpdated" => "2012-07-12 19:50:25", "Width" => 1100}], "URL" => "http://zapfolio.smugmug.com/Other/Test/24080102_Ka2Wx9"},
      :get_extras_2 => {"id" => 24080103, "Key" => "Ka2Wx4", "ImageCount" => 2, "Images" => [{"id" => 1955880388, "Key" => "HskGhaB", "Caption" => "This is a test caption", "Date" => "2012-07-13 19:10:56", "Format" => "JPG", "Height" => 1025, "Hidden" => false, "LastUpdated" => "2012-07-09 19:50:20", "Width" => 768}], "URL" => "http://zapfolio.smugmug.com/Other/Test/2408103_Ka2Wx4"}
    }
  }
end